### ISSUE TITLE
ParseCancellationException

### ISSUE THREAD

**Issue by dansto** [OP-TED/eforms-notice-viewer#11] opened 2022-05-25 09:54 UTC
hello

when i run

mvn compile exec:java -Dexec.mainClass="eu.europa.ted.eforms.viewer.Application" -Dexec.args="en ./eforms-sdk/0.6/examples/notices/cn_24_open.xml"

i get this errror:

[INFO] Scanning for projects...
[INFO]
[INFO] -------------< eu.europa.ted.eforms:eforms-notice-viewer >--------------
[INFO] Building eForms Notice Viewer 0.1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.3.0:unpack (unpack-sdk) @ eforms-notice-viewer ---
[INFO] Configured Artifact: eu.europa.ted.eforms:eforms-sdk:0.6.2:jar
[INFO] eforms-sdk-0.6.2.jar already unpacked.
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ eforms-notice-viewer ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ eforms-notice-viewer ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ eforms-notice-viewer ---
11:50:46,619 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
11:50:46,619 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/home/stock/eforms-notice-viewer/target/classes/logback.xml]
11:50:46,715 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/home/stock/eforms-notice-viewer/target/classes/logback.xml]
11:50:46,715 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
11:50:46,718 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
11:50:46,720 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
11:50:46,723 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
11:50:46,740 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.sf.saxon.lib] to DEBUG
11:50:46,740 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
11:50:46,740 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
11:50:46,740 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
11:50:46,741 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@27860e7e - Registering current configuration as safe fallback point
11:50:46.742 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.Application - eForms Notice Viewer
11:50:46.743 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.Application - Usage: <two letter language code> <path of XML file to view> [<view id to use>] [SDK resources root folder]
11:50:46.743 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.Application - Example: en X02_registration.xml
11:50:46.743 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.Application - args=[en, ./eforms-sdk/0.6/examples/notices/cn_24_open.xml]
11:50:46.746 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.NoticeViewer - noticeXmlPath=./eforms-sdk/0.6/examples/notices/cn_24_open.xml
11:50:46.776 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.NoticeViewer - noticeSubType=16, viewId=16, eformsSdkVersion=eforms-sdk-0.6
11:50:46.842 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.t.e.viewer.helpers.MapFromJson - Populating maps for context, sdkVersion=eforms-sdk-0.6, jsonPathname=/home/stock/eforms-notice-viewer/eforms-sdk/0.6/fields/fields.json
11:50:47.040 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.t.e.viewer.helpers.MapFromJson - Populating maps for context, sdkVersion=eforms-sdk-0.6, jsonPathname=/home/stock/eforms-notice-viewer/eforms-sdk/0.6/fields/fields.json
[WARNING]
org.antlr.v4.runtime.misc.ParseCancellationException: line 24:27 mismatched input 'value' expecting {ShorthandContextFieldValueReference, StartExpression, CodelistAssetId, OtherAssetId, BtId, FieldId}
    at eu.europa.ted.efx.exceptions.ThrowingErrorListener.syntaxError (ThrowingErrorListener.java:17)
    at org.antlr.v4.runtime.ProxyErrorListener.syntaxError (ProxyErrorListener.java:41)
    at org.antlr.v4.runtime.Parser.notifyErrorListeners (Parser.java:544)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch (DefaultErrorStrategy.java:327)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportError (DefaultErrorStrategy.java:139)
    at eu.europa.ted.efx.sdk0.v6.EfxParser.assetId (EfxParser.java:1100)
    at eu.europa.ted.efx.sdk0.v6.EfxParser.labelBlock (EfxParser.java:835)
    at eu.europa.ted.efx.sdk0.v6.EfxParser.templateFragment (EfxParser.java:494)
    at eu.europa.ted.efx.sdk0.v6.EfxParser.template (EfxParser.java:384)
    at eu.europa.ted.efx.sdk0.v6.EfxParser.templateLine (EfxParser.java:343)
    at eu.europa.ted.efx.sdk0.v6.EfxParser.templateFile (EfxParser.java:267)
    at eu.europa.ted.efx.sdk0.v6.EfxTemplateTranslator.renderTemplate (EfxTemplateTranslator.java:144)
    at eu.europa.ted.efx.sdk0.v6.EfxTemplateTranslator.renderTemplate (EfxTemplateTranslator.java:111)
    at eu.europa.ted.efx.EfxTranslator.translateTemplate (EfxTranslator.java:33)
    at eu.europa.ted.eforms.viewer.NoticeViewer.buildXsl (NoticeViewer.java:172)
    at eu.europa.ted.eforms.viewer.NoticeViewer.generateHtml (NoticeViewer.java:91)
    at eu.europa.ted.eforms.viewer.Application.main (Application.java:58)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:829)

**Comment by rousso** [comment] 2022-05-29 10:40
Hi again @dansto,

There are two problems here:

1. The exception is caused by an issue with the [16.efx view template](https://github.com/OP-TED/eForms-SDK/blob/0.6.2/view-templates/16.efx#L24). In line 24 there is a label reference, using `value` as an asset identifier. However, for EFX, `value` is a reserved word and we should not have allowed an asset_id to be a an EFX keyword. If you change the `value`  to something else in line 24 of 16.efx the application will not throw an exception. We will fix the issue in 16.efx in the next release of the SDK.
2. The second problem is that the application throws an exception for a parser error that could have been handled gracefully. We will address this in the next release of the notice-viewer. 
Regards,
Yannis

**Comment by rousso** [comment] 2022-05-29 22:27
Hello again @dansto,

Follow-up: I just tried to reproduce the error you reported. I turns out that even if you bypass that error in 16.efx as I suggested in my previous message, you will still get a lot of other issues with that file. The templates in 0.6.0 are not anywhere near acceptable as we rushed them out in this release without properly testing them. We were mostly focused on getting the EFX translators right. We will go through the templates and fix as many issues as possible in the coming weeks. 

Thank you for reporting this.

**Comment by rousso** [comment] 2022-07-12 14:33
Fixed in Notice Viewer version 0.2.0.
 
However, you may still find some EFX templates that contain EFX expressions that cannot be compiled and therefore cannot be rendered. These issues will be resolved in upcoming versions of the SDK. 

I am closing this issue as there is nothing more to fix in the software in relation to the specific problem.  The Notice Viewer application will be able to automatically download and use future versions of the eForms SDK that fix the remaining problematic EFX templates.

**Closed by rousso** 2022-07-12 14:33 UTC

**Comment by dansto** [comment] 2022-07-14 13:19
hello,

I ran from scratch:

git clone https://github.com/OP-TED/eForms-SDK
git clone https://github.com/OP-TED/eforms-notice-viewer
cd eforms-notice-viewer
mvn compile exec:java -Dexec.mainClass="eu.europa.ted.eforms.viewer.Application" -Dexec.args="en ../eForms-SDK/examples/notices/cn_24_minimal.xml"


and now I get this error:




[INFO] Scanning for projects...
[INFO]
[INFO] -------------< eu.europa.ted.eforms:eforms-notice-viewer >--------------
[INFO] Building eForms Notice Viewer 0.2.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ eforms-notice-viewer ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ eforms-notice-viewer ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ eforms-notice-viewer ---
15:16:47,679 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:16:47,679 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/home/stock/eforms-notice-viewer/target/classes/logback.xml]
15:16:47,679 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
15:16:47,679 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/home/stock/eforms-notice-viewer/target/classes/logback.xml]
15:16:47,679 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/stock/.m2/repository/eu/europa/ted/eforms/efx-toolkit-java/0.2.0/efx-toolkit-java-0.2.0.jar!/logback.xml]
15:16:47,754 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:16:47,757 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/home/stock/eforms-notice-viewer/target/classes/logback.xml]
15:16:47,757 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
15:16:47,758 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:16:47,760 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:16:47,764 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:16:47,780 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.sf.saxon.lib] to DEBUG
15:16:47,780 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:16:47,780 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
15:16:47,780 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:16:47,781 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@114c18c4 - Registering current configuration as safe fallback point

15:16:47.911 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.NoticeViewer - noticeXmlPath=../eForms-SDK/examples/notices/cn_24_minimal.xml
15:16:47.947 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.NoticeViewer - noticeSubType=16, viewId=16, eformsSdkVersion=0.7
15:16:48.230 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.t.eforms.sdk.helpers.MapFromJson - Populating maps for context, jsonPath=/home/stock/eforms-notice-viewer/eforms-sdk/0.7/fields/fields.json
15:16:48.545 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.t.eforms.sdk.helpers.MapFromJson - Populating maps for context, jsonPath=/home/stock/eforms-notice-viewer/eforms-sdk/0.7/fields/fields.json
org.antlr.v4.runtime.misc.ParseCancellationException: line 150:32 mismatched input 'OR' expecting {'[', EndExpression}
        at eu.europa.ted.efx.exceptions.ThrowingErrorListener.syntaxError(ThrowingErrorListener.java:17)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
        at eu.europa.ted.efx.sdk0.v7.EfxParser.contextDeclarationBlock(EfxParser.java:1311)
        at eu.europa.ted.efx.sdk0.v7.EfxParser.templateLine(EfxParser.java:361)
        at eu.europa.ted.efx.sdk0.v7.EfxParser.templateFile(EfxParser.java:287)
        at eu.europa.ted.efx.sdk0.v7.EfxTemplateTranslator07.renderTemplate(EfxTemplateTranslator07.java:152)
        at eu.europa.ted.efx.sdk0.v7.EfxTemplateTranslator07.renderTemplate(EfxTemplateTranslator07.java:136)
        at eu.europa.ted.efx.EfxTranslator.translateTemplate(EfxTranslator.java:50)
        at eu.europa.ted.eforms.viewer.NoticeViewer.buildXsl(NoticeViewer.java:253)
        at eu.europa.ted.eforms.viewer.NoticeViewer.generateHtml(NoticeViewer.java:88)
        at eu.europa.ted.eforms.viewer.CliCommand.call(CliCommand.java:63)
        at eu.europa.ted.eforms.viewer.CliCommand.call(CliCommand.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at eu.europa.ted.eforms.viewer.Application.main(Application.java:10)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by dansto** [comment] 2022-07-14 13:25
addition:

this is working fine:

mvn compile exec:java -Dexec.mainClass="eu.europa.ted.eforms.viewer.Application" -Dexec.args="en ../eForms-SDK/examples/notices/X02_registration.xml"

 mvn compile exec:java -Dexec.mainClass="eu.europa.ted.eforms.viewer.Application" -Dexec.args="en ../eForms-SDK/examples/notices/X02_registration.xml"
[INFO] Scanning for projects...
[INFO]
[INFO] -------------< eu.europa.ted.eforms:eforms-notice-viewer >--------------
[INFO] Building eForms Notice Viewer 0.2.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ eforms-notice-viewer ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.10.1:compile (default-compile) @ eforms-notice-viewer ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ eforms-notice-viewer ---
15:23:10,808 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:23:10,808 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/home/stock/eforms-notice-viewer/target/classes/logback.xml]
15:23:10,809 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
15:23:10,809 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [file:/home/stock/eforms-notice-viewer/target/classes/logback.xml]
15:23:10,809 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/home/stock/.m2/repository/eu/europa/ted/eforms/efx-toolkit-java/0.2.0/efx-toolkit-java-0.2.0.jar!/logback.xml]
15:23:10,900 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:23:10,904 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Will scan for changes in [file:/home/stock/eforms-notice-viewer/target/classes/logback.xml]
15:23:10,904 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - Setting ReconfigureOnChangeTask scanning period to 30 seconds
15:23:10,908 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:23:10,910 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
15:23:10,913 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:23:10,931 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [net.sf.saxon.lib] to DEBUG
15:23:10,932 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:23:10,932 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
15:23:10,932 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:23:10,932 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5404209e - Registering current configuration as safe fallback point

15:23:11.057 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.NoticeViewer - noticeXmlPath=../eForms-SDK/examples/notices/X02_registration.xml
15:23:11.088 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.NoticeViewer - noticeSubType=X02, viewId=X02, eformsSdkVersion=0.7
15:23:11.359 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.t.eforms.sdk.helpers.MapFromJson - Populating maps for context, jsonPath=/home/stock/eforms-notice-viewer/eforms-sdk/0.7/fields/fields.json
15:23:11.618 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.t.eforms.sdk.helpers.MapFromJson - Populating maps for context, jsonPath=/home/stock/eforms-notice-viewer/eforms-sdk/0.7/fields/fields.json
15:23:12.751 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.NoticeViewer - Created xsl file: target/output-xsl/X02.xsl
15:23:15.153 [eu.europa.ted.eforms.viewer.Application.main()] INFO  e.e.ted.eforms.viewer.CliCommand - Created HTML file: target/output-html/X02.html
